// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6k3XZVSlujobUxm19UoXkl-hd0ZT75o0',
    appId: '1:376373224058:web:8e1af5754a193ba7f711c3',
    messagingSenderId: '376373224058',
    projectId: 'yashoda-ff738',
    authDomain: 'yashoda-243d6.firebaseapp.com',
    storageBucket: 'yashoda-243d6.firebasestorage.app',
    measurementId: 'G-HRYRT0VESJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTx09m5l7gKckCkRLTpYZ0Z0i3akVCa-U',
    appId: '1:376373224058:android:3c01209ea9cc23f7f711c3',
    messagingSenderId: '376373224058',
    projectId: 'yashoda-243d6',
    storageBucket: 'yashoda-243d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHLBE8yrCg5mxOiCQzHp0VdvVIYavTGY',
    appId: '1:376373224058:ios:c243c476fb521157f711c3',
    messagingSenderId: '376373224058',
    projectId: 'yashoda-243d6',
    storageBucket: 'yashoda-243d6.firebasestorage.app',
    iosBundleId: 'com.example.yashoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVHLBE8yrCg5mxOiCQzHp0VdvVIYavTGY',
    appId: '1:376373224058:ios:c243c476fb521157f711c3',
    messagingSenderId: '376373224058',
    projectId: 'yashoda-243d6',
    storageBucket: 'yashoda-243d6.firebasestorage.app',
    iosBundleId: 'com.example.yashoda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6k3XZVSlujobUxm19UoXkl-hd0ZT75o0',
    appId: '1:376373224058:web:8402f64bf5cba10af711c3',
    messagingSenderId: '376373224058',
    projectId: 'yashoda-243d6',
    authDomain: 'yashoda-243d6.firebaseapp.com',
    storageBucket: 'yashoda-243d6.firebasestorage.app',
    measurementId: 'G-CR8PT2W96D',
  );

}